version: '3.8'

services:
  db:
    image: arangodb/arangodb:3.11
    container_name: arangodb-test
    ports:
      - "8529:8529"
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - arango_data:/var/lib/arangodb3

volumes:
  arango_data: