name: "1. Согласована и сформулирована тема курсовой"

on:
  push:
    branches:
      - main

jobs:
  check_hello_world_dir_not_empty:
    name: "Проверка наличия каталога ./hello_world/"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        name: Check out current commit

      - name: check
        run: .github/workflows/scripts/1_helloworld.sh
